# @package _global_

defaults:
  - model: diffusion

dataset_path: None # ${work_dir}/data/greatest_hit/test_onset_preds.tar
experiment_path: None # ${work_dir}/output/experiments/gh-gen-pred
gen_length: 262144
cut_length: 96000
sample_rate: 48000
one_chunk_per_track: True

experiment:
  _target_: main.generation.generate_dataset
  _partial_: True
  experiment_path: ${experiment_path}
  model: ${model}
  model_path: null
  device: 'cuda'
  batch_size: 10  # < Change to best fit your architecture
  num_steps: 150
  embedding_scale: 2.0
  sample_rate: ${sample_rate}
  one_chunk_per_track: ${one_chunk_per_track}
  length: ${gen_length}
  cut_length: ${cut_length}
  cut_prefix: False
  downsample_rate: 22050

  dataset:
    _target_: main.dataset_diffusion.create_sfx_dataset
    path: ${dataset_path}
    sample_rate: ${sample_rate}
    chunk_size: ${gen_length}
    shift_augment: False
    cut_prefix: False
    one_chunk_per_track: ${one_chunk_per_track}
    onset_check_length: ${cut_length}
    shardshuffle: False

evaluation:
  _target_: main.evaluation.evaluate_fad
  _partial_: True
  experiment_path: ${experiment_path}
  gt_path: ${work_dir}/output/experiments/gh-gt-pred