seed_everything: true

trainer:
  max_epochs: 100
  
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      entity: entity-name
      project: syncfusion
      id: null
      name: GH-train # if null wandb gives it name
      save_dir: logs/onset/train # dir needs to already exist
      group: ONSET-TRAIN
  
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: logs/onset/checkpoints
        save_last: true
        save_top_k: 1
        monitor: loss/val
        mode: min
        every_n_epochs: 5
        filename: "epoch={epoch}-val={loss/val:.3f}"
        auto_insert_metric_name: false
    
    - class_path: pytorch_lightning.callbacks.ModelSummary
      init_args:
        max_depth: 2

    - class_path: pytorch_lightning.callbacks.LearningRateMonitor