seed_everything: true

trainer:
  max_epochs: 100
  
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      entity: team-mcomunita
      project: diffusion-sfx
      id: null
      name: GH-train # if null wandb gives it name
      save_dir: /import/c4dm-datasets-ext/DIFF-SFX/logs/onset-temp/train # dir needs to already exist
      group: ONSET-TRAIN
  
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: /import/c4dm-datasets-ext/DIFF-SFX/logs/onset-temp/checkpoints
        save_last: true
        save_top_k: 1
        monitor: loss/val
        mode: min
        every_n_epochs: 10
        filename: "{epoch}-{step}-{loss/val:.3f}"
    
    - class_path: pytorch_lightning.callbacks.ModelSummary
      init_args:
        max_depth: 2

    - class_path: pytorch_lightning.callbacks.LearningRateMonitor